name: Build and Push Docker Image
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

env:
  IMAGE_NAME: website
  REGISTRY_URL: artifactory.jioxl.com
  VERSION: 0.0.${{ secrets.MINOR_VERSION }} 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

     # - name: Install dependencies
     #   run: npm install

     # - name: Build code
     #   run: npm run build

      - name: Configure Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to private Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ env.REGISTRY_URL }}
          
      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.VERSION }} .

      - name: Tag Docker image
        run: docker tag ${{ env.IMAGE_NAME }}:${{ env.VERSION }} ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

      - name: Push Docker image
        run: docker push ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.VERSION  }}
        
      - name: Update Minor version
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'MINOR_VERSION'
          value: $((${{ secrets.MINOR_VERSION }}+1))
          repository: ${{ github.repository }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
